version: '3.7'

networks:
  api-sqlserver:
    external : true
services:
  service1:
    image: webapiproducto:v1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:80
    networks:
      - api-sqlserver
  service2:
    image: webapiproducto:v1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8082:80
    networks:
      - api-sqlserver
    