name: Trigger auto deployment for con-webapiproducto

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3 
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.CONWEBAPIPRODUCTO_REGISTRY_USERNAME }}
        password: ${{ secrets.CONWEBAPIPRODUCTO_REGISTRY_PASSWORD }}
    - name: Build website image
      run: | 
        docker build --platform linux --tag mpenrozp/webapiproducto:latest -f ./Dockerfile .
    - name: Publish website image
      run: |
        docker push mpenrozp/webapiproducto:latest
    - name: Azure Login
      uses: Azure/login@v1.4.6
      with:
          client-id: ${{ secrets.CONMSWEBAPIPRODUCTO_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONMSWEBAPIPRODUCTO_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONMSWEBAPIPRODUCTO_AZURE_SUBSCRIPTION_ID }}
    - name: Deploy NET container App
      run: |
          az containerapp up --name "con-ms-webapiproduct" --resource-group test-microservices --environment managedEnvironment-testmicroservic-a77c --image mpenrozp/webapiproducto:latest --user-assigned "9774e9d4-cd9d-40a3-977c-fece07b7a0dd" --secrets "queue-connection-string=keyvaultref:https://key-value-ms.vault.azure.net/secrets/secreto1/e50e6a94eaf74d1294fd37e067d088de,identityref:9774e9d4-cd9d-40a3-977c-fece07b7a0dd"
