name: Trigger auto deployment for con-webapiproducto

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/con-webapiproducto.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
    - name: Check out the repo
      uses: actions/checkout@v3 
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.CONWEBAPIPRODUCTO_REGISTRY_USERNAME }}
        password: ${{ secrets.CONWEBAPIPRODUCTO_REGISTRY_PASSWORD }}
    - name: Build website image
      run: | 
        docker build --platform linux --tag mpenrozp/webapiproducto:latest -f ./Dockerfile .
    - name: Publish website image
      run: |
        docker push mpenrozp/webapiproducto:latest
    - name: App service auth
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'WebApiProductoTest'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: 'mpenrozp/webapiproducto:latest'


