name: Trigger auto deployment for con-webapiproduct
# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo 
  push:
    branches: 
      [ main ]
    paths:
    - '**'
  # Allow manual trigger 
  workflow_dispatch:   
env:
  tag: ${{ github.sha }}
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3 
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.CONMSWEBAPIPRODUCT_REGISTRY_USERNAME }}
        password: ${{ secrets.CONMSWEBAPIPRODUCT_REGISTRY_PASSWORD }}
    - name: Build website image
      run: | 
        docker build --platform linux --tag mpenrozp/con-ms-webapiproducto:${{ env.tag }} -f ./Dockerfile .
    - name: Publish website image
      run: |
        docker push mpenrozp/con-ms-webapiproducto:${{ env.tag }}
    - name: Azure Login
      uses: Azure/login@v1.4.6
      with:
          client-id: ${{ secrets.CONMSWEBAPIPRODUCT_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONMSWEBAPIPRODUCT_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONMSWEBAPIPRODUCT_AZURE_SUBSCRIPTION_ID }}
    - name: Deploy NET container App
      run: |
          az containerapp update -n "con-ms-webapiproducto" -g test-ms --image mpenrozp/con-ms-webapiproducto:${{ env.tag }} --min-replicas 1 --max-replicas 4 --set-env-vars client-id=secretref:clientid
          

