name: Trigger auto deployment for con-test-user

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/con-test-user-AutoDeployTrigger-824e7196-187b-4c81-a0d2-f8b58486257f.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTESTUSER_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTESTUSER_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTESTUSER_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: docker.io
          registryUsername: ${{ secrets.CONTESTUSER_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTESTUSER_REGISTRY_PASSWORD }}
          containerAppName: con-test-user
          resourceGroup: test-microservices
          imageToBuild: mpenrozp/con-test-user:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


